config/routes.rb
Rails.application.routes.draw do
  resources :complex_list_items
  resources :string_list_items
  resources :number_list_items
  resources :lists
  resources :list_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "index#index"
end

app/models/complex_list_item.rb
class ComplexListItem < ApplicationRecord
  belongs_to :list
end

app/controllers/complex_list_items_controller.rb
class ComplexListItemsController < ApplicationController
  before_action :set_complex_list_item, only: [:show, :edit, :update, :destroy]

  # GET /complex_list_items
  # GET /complex_list_items.json
  def index
    @complex_list_items = ComplexListItem.all
  end

  # GET /complex_list_items/1
  # GET /complex_list_items/1.json
  def show
  end

  # GET /complex_list_items/new
  def new
    @complex_list_item = ComplexListItem.new
  end

  # GET /complex_list_items/1/edit
  def edit
  end

  # POST /complex_list_items
  # POST /complex_list_items.json
  def create
    @complex_list_item = ComplexListItem.new(complex_list_item_params)

    respond_to do |format|
      if @complex_list_item.save
        format.html { redirect_to @complex_list_item, notice: 'Complex list item was successfully created.' }
        format.json { render :show, status: :created, location: @complex_list_item }
      else
        format.html { render :new }
        format.json { render json: @complex_list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /complex_list_items/1
  # PATCH/PUT /complex_list_items/1.json
  def update
    respond_to do |format|
      if @complex_list_item.update(complex_list_item_params)
        format.html { redirect_to @complex_list_item, notice: 'Complex list item was successfully updated.' }
        format.json { render :show, status: :ok, location: @complex_list_item }
      else
        format.html { render :edit }
        format.json { render json: @complex_list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complex_list_items/1
  # DELETE /complex_list_items/1.json
  def destroy
    @complex_list_item.destroy
    respond_to do |format|
      format.html { redirect_to complex_list_items_url, notice: 'Complex list item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complex_list_item
      @complex_list_item = ComplexListItem.find(params[:id]) or not_found
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def complex_list_item_params
      params.require(:complex_list_item).permit(:guid, :list_id, :data, :sort_number)
    end
end

app/helpers/complex_list_items_helper.rb
module ComplexListItemsHelper
end

app/views/complex_list_items/_form.html.erb
<%= form_with(model: complex_list_item, local: true) do |form| %>
  <% if complex_list_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(complex_list_item.errors.count, "error") %> prohibited this complex_list_item from being saved:</h2>

      <ul>
      <% complex_list_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :guid %>
    <%= form.text_field :guid, id: :complex_list_item_guid %>
  </div>

  <div class="field">
    <%= form.label :list_id %>
    <%= form.text_field :list_id, id: :complex_list_item_list_id %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_area :data, id: :complex_list_item_data %>
  </div>

  <div class="field">
    <%= form.label :sort_number %>
    <%= form.text_field :sort_number, id: :complex_list_item_sort_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/complex_list_items/edit.html.erb
<h1>Editing Complex List Item</h1>

<%= render 'form', complex_list_item: @complex_list_item %>

<%= link_to 'Show', @complex_list_item %> |
<%= link_to 'Back', complex_list_items_path %>

app/views/complex_list_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Complex List Items</h1>

<table>
  <thead>
    <tr>
      <th>Guid</th>
      <th>List</th>
      <th>Data</th>
      <th>Sort number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @complex_list_items.each do |complex_list_item| %>
      <tr>
        <td><%= complex_list_item.guid %></td>
        <td><%= complex_list_item.list %></td>
        <td><%= complex_list_item.data %></td>
        <td><%= complex_list_item.sort_number %></td>
        <td><%= link_to 'Show', complex_list_item %></td>
        <td><%= link_to 'Edit', edit_complex_list_item_path(complex_list_item) %></td>
        <td><%= link_to 'Destroy', complex_list_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Complex List Item', new_complex_list_item_path %>

app/views/complex_list_items/new.html.erb
<h1>New Complex List Item</h1>

<%= render 'form', complex_list_item: @complex_list_item %>

<%= link_to 'Back', complex_list_items_path %>

app/views/complex_list_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Guid:</strong>
  <%= @complex_list_item.guid %>
</p>

<p>
  <strong>List:</strong>
  <%= @complex_list_item.list %>
</p>

<p>
  <strong>Data:</strong>
  <%= @complex_list_item.data %>
</p>

<p>
  <strong>Sort Number:</strong>
  <%= @complex_list_item.sort_number %>
</p>

<%= link_to 'Edit', edit_complex_list_item_path(@complex_list_item) %> |
<%= link_to 'Back', complex_list_items_path %>