config/routes.rb
Rails.application.routes.draw do
  resources :complex_list_items
  resources :string_list_items
  resources :number_list_items
  resources :lists
  resources :list_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "index#index"
end

app/models/number_list_item.rb
class NumberListItem < ApplicationRecord
  belongs_to :list
end

app/controllers/number_list_items_controller.rb
class NumberListItemsController < ApplicationController
  before_action :set_number_list_item, only: [:show, :edit, :update, :destroy]

  # GET /number_list_items
  # GET /number_list_items.json
  def index
    @number_list_items = NumberListItem.all
  end

  # GET /number_list_items/1
  # GET /number_list_items/1.json
  def show
  end

  # GET /number_list_items/new
  def new
    @number_list_item = NumberListItem.new
  end

  # GET /number_list_items/1/edit
  def edit
  end

  # POST /number_list_items
  # POST /number_list_items.json
  def create
    @number_list_item = NumberListItem.new(number_list_item_params)

    respond_to do |format|
      if @number_list_item.save
        format.html { redirect_to @number_list_item, notice: 'Number list item was successfully created.' }
        format.json { render :show, status: :created, location: @number_list_item }
      else
        format.html { render :new }
        format.json { render json: @number_list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /number_list_items/1
  # PATCH/PUT /number_list_items/1.json
  def update
    respond_to do |format|
      if @number_list_item.update(number_list_item_params)
        format.html { redirect_to @number_list_item, notice: 'Number list item was successfully updated.' }
        format.json { render :show, status: :ok, location: @number_list_item }
      else
        format.html { render :edit }
        format.json { render json: @number_list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /number_list_items/1
  # DELETE /number_list_items/1.json
  def destroy
    @number_list_item.destroy
    respond_to do |format|
      format.html { redirect_to number_list_items_url, notice: 'Number list item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_number_list_item
      @number_list_item = NumberListItem.find(params[:id]) or not_found
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def number_list_item_params
      params.require(:number_list_item).permit(:guid, :list_id, :data, :sort_number)
    end
end

app/helpers/number_list_items_helper.rb
module NumberListItemsHelper
end

app/views/number_list_items/_form.html.erb
<%= form_with(model: number_list_item, local: true) do |form| %>
  <% if number_list_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(number_list_item.errors.count, "error") %> prohibited this number_list_item from being saved:</h2>

      <ul>
      <% number_list_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :guid %>
    <%= form.text_field :guid, id: :number_list_item_guid %>
  </div>

  <div class="field">
    <%= form.label :list_id %>
    <%= form.text_field :list_id, id: :number_list_item_list_id %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_field :data, id: :number_list_item_data %>
  </div>

  <div class="field">
    <%= form.label :sort_number %>
    <%= form.text_field :sort_number, id: :number_list_item_sort_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/number_list_items/edit.html.erb
<h1>Editing Number List Item</h1>

<%= render 'form', number_list_item: @number_list_item %>

<%= link_to 'Show', @number_list_item %> |
<%= link_to 'Back', number_list_items_path %>

app/views/number_list_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Number List Items</h1>

<table>
  <thead>
    <tr>
      <th>Guid</th>
      <th>List</th>
      <th>Data</th>
      <th>Sort Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @number_list_items.each do |number_list_item| %>
      <tr>
        <td><%= number_list_item.guid %></td>
        <td><%= number_list_item.list %></td>
        <td><%= number_list_item.data %></td>
        <td><%= number_list_item.sort_number %></td>
        <td><%= link_to 'Show', number_list_item %></td>
        <td><%= link_to 'Edit', edit_number_list_item_path(number_list_item) %></td>
        <td><%= link_to 'Destroy', number_list_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Number List Item', new_number_list_item_path %>

app/views/number_list_items/new.html.erb
<h1>New Number List Item</h1>

<%= render 'form', number_list_item: @number_list_item %>

<%= link_to 'Back', number_list_items_path %>

app/views/number_list_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Guid:</strong>
  <%= @number_list_item.guid %>
</p>

<p>
  <strong>List:</strong>
  <%= @number_list_item.list %>
</p>

<p>
  <strong>Data:</strong>
  <%= @number_list_item.data %>
</p>

<%= link_to 'Edit', edit_number_list_item_path(@number_list_item) %> |
<%= link_to 'Back', number_list_items_path %>