config/routes.rb
Rails.application.routes.draw do
  resources :complex_list_items
  resources :string_list_items
  resources :number_list_items
  resources :lists
  resources :list_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "index#index"
end

app/models/string_list_item.rb
class StringListItem < ApplicationRecord
  belongs_to :list
end

app/controllers/string_list_items_controller.rb
class StringListItemsController < ApplicationController
  before_action :set_string_list_item, only: [:show, :edit, :update, :destroy]

  # GET /string_list_items
  # GET /string_list_items.json
  def index
    @string_list_items = StringListItem.all
  end

  # GET /string_list_items/1
  # GET /string_list_items/1.json
  def show
  end

  # GET /string_list_items/new
  def new
    @string_list_item = StringListItem.new
  end

  # GET /string_list_items/1/edit
  def edit
  end

  # POST /string_list_items
  # POST /string_list_items.json
  def create
    @string_list_item = StringListItem.new(string_list_item_params)

    respond_to do |format|
      if @string_list_item.save
        format.html { redirect_to @string_list_item, notice: 'String list item was successfully created.' }
        format.json { render :show, status: :created, location: @string_list_item }
      else
        format.html { render :new }
        format.json { render json: @string_list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /string_list_items/1
  # PATCH/PUT /string_list_items/1.json
  def update
    respond_to do |format|
      if @string_list_item.update(string_list_item_params)
        format.html { redirect_to @string_list_item, notice: 'String list item was successfully updated.' }
        format.json { render :show, status: :ok, location: @string_list_item }
      else
        format.html { render :edit }
        format.json { render json: @string_list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /string_list_items/1
  # DELETE /string_list_items/1.json
  def destroy
    @string_list_item.destroy
    respond_to do |format|
      format.html { redirect_to string_list_items_url, notice: 'String list item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_string_list_item
      @string_list_item = StringListItem.find(params[:id]) or not_found
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def string_list_item_params
      params.require(:string_list_item).permit(:guid, :list_id, :data, :sort_number)
    end
end

app/helpers/string_list_items_helper.rb
module StringListItemsHelper
end

app/views/string_list_items/_form.html.erb
<%= form_with(model: string_list_item, local: true) do |form| %>
  <% if string_list_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(string_list_item.errors.count, "error") %> prohibited this string_list_item from being saved:</h2>

      <ul>
      <% string_list_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :guid %>
    <%= form.text_field :guid, id: :string_list_item_guid %>
  </div>

  <div class="field">
    <%= form.label :list_id %>
    <%= form.text_field :list_id, id: :string_list_item_list_id %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_field :data, id: :string_list_item_data %>
  </div>

  <div class="field">
    <%= form.label :sort_number %>
    <%= form.text_field :sort_number, id: :string_list_item_sort_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/string_list_items/edit.html.erb
<h1>Editing String List Item</h1>

<%= render 'form', string_list_item: @string_list_item %>

<%= link_to 'Show', @string_list_item %> |
<%= link_to 'Back', string_list_items_path %>

app/views/string_list_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>String List Items</h1>

<table>
  <thead>
    <tr>
      <th>Guid</th>
      <th>List</th>
      <th>Data</th>
      <th>Sort Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @string_list_items.each do |string_list_item| %>
      <tr>
        <td><%= string_list_item.guid %></td>
        <td><%= string_list_item.list %></td>
        <td><%= string_list_item.data %></td>
        <td><%= string_list_item.sort_number %></td>
        <td><%= link_to 'Show', string_list_item %></td>
        <td><%= link_to 'Edit', edit_string_list_item_path(string_list_item) %></td>
        <td><%= link_to 'Destroy', string_list_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New String List Item', new_string_list_item_path %>

app/views/string_list_items/new.html.erb
<h1>New String List Item</h1>

<%= render 'form', string_list_item: @string_list_item %>

<%= link_to 'Back', string_list_items_path %>

app/views/string_list_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Guid:</strong>
  <%= @string_list_item.guid %>
</p>

<p>
  <strong>List:</strong>
  <%= @string_list_item.list %>
</p>

<p>
  <strong>Data:</strong>
  <%= @string_list_item.data %>
</p>

<p>
  <strong>Sort Number:</strong>
  <%= @string_list_item.sort_number %>
</p>

<%= link_to 'Edit', edit_string_list_item_path(@string_list_item) %> |
<%= link_to 'Back', string_list_items_path %>